/** The display text; the key code; the width of the key. */
type KeySpecification = [string, string, number?]

/** The keyboard array contains the key rows,
 * the key rows contain the key specification.
*/
export const keyboardLayout: KeySpecification[][] = [
  [
    ['Esc', 'Escape'],
    ['', ''],
    ['F1', 'F1'],
    ['F2', 'F2'],
    ['F3', 'F3'],
    ['F4', 'F4'],
    ['', '', .5],
    ['F5', 'F5'],
    ['F6', 'F6'],
    ['F7', 'F7'],
    ['F8', 'F8'],
    ['', '', .5],
    ['F9', 'F9'],
    ['F10', 'F10'],
    ['F11', 'F11'],
    ['F12', 'F12'],
    ['', '', .5],
    ['PS', ''],
    ['SL', 'ScrollLock'],
    ['PB', 'Pause']
  ],
  [],
  [
    ['`', 'Backquote'],
    ['1', 'Digit1'],
    ['2', 'Digit2'],
    ['3', 'Digit3'],
    ['4', 'Digit4'],
    ['5', 'Digit5'],
    ['6', 'Digit6'],
    ['7', 'Digit7'],
    ['8', 'Digit8'],
    ['9', 'Digit9'],
    ['0', 'Digit0'],
    ['-', 'Minus'],
    ['=', 'Equal'],
    ['←', 'Backspace', 2],
    ['', '', .5],
    ['INS', 'Insert'],
    ['HM', 'Home'],
    ['PU', 'PageUp']
  ], [
    ['⭾', 'Tab', 1.5],
    ['Q', 'KeyQ'],
    ['W', 'KeyW'],
    ['E', 'KeyE'],
    ['R', 'KeyR'],
    ['T', 'KeyT'],
    ['Y', 'KeyY'],
    ['U', 'KeyU'],
    ['I', 'KeyI'],
    ['O', 'KeyO'],
    ['P', 'KeyP'],
    ['[', 'BracketLeft'],
    [']', 'BracketRight'],
    ['⏎', 'Enter', 1.5],
    ['', '', .5],
    ['DEL', 'Delete'],
    ['END', 'End'],
    ['PD', 'PageDown']
  ], [
    ['CpsLk', 'CapsLock', 2],
    ['A', 'KeyA'],
    ['S', 'KeyS'],
    ['D', 'KeyD'],
    ['F', 'KeyF'],
    ['G', 'KeyG'],
    ['H', 'KeyH'],
    ['J', 'KeyJ'],
    ['K', 'KeyK'],
    ['L', 'KeyL'],
    [';', 'Semicolon'],
    ['\'', 'Quote'],
    ['\\', 'Backslash'],
    ['', '']
  ], [
    ['Shift', 'ShiftLeft', 2.5],
    ['Z', 'KeyZ'],
    ['X', 'KeyX'],
    ['C', 'KeyC'],
    ['V', 'KeyV'],
    ['B', 'KeyB'],
    ['N', 'KeyN'],
    ['M', 'KeyM'],
    [',', 'Comma'],
    ['.', 'Period'],
    ['/', 'Slash'],
    ['Shift', 'ShiftRight', 2.5],
    ['', '', 1.5],
    ['↑', 'ArrowUp']
  ], [
    ['Ctrl', 'ControlLeft', 1.4],
    ['OS', 'OSLeft', 1.4],
    ['Alt', 'AltLeft', 1.4],
    ['Space', 'Space', 5.2],
    ['Alt', 'AltRight', 1.4],
    ['Fn', '', 1.4],
    ['🧾', 'ContextMenu', 1.4],
    ['Ctrl', 'ControlRight', 1.4],
    ['', '', .5],
    ['←', 'ArrowLeft'],
    ['↓', 'ArrowDown'],
    ['→', 'ArrowRight']
  ]
]